apiVersion: v1
kind: Service
metadata:
  name: kubapi
spec:
  selector:
    app: kubapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubapi-deployment
  labels:
    app: kubapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubapi
  template:
    metadata:
      labels:
        app: kubapi
    spec:
      containers:
        - name: kubapi
          image: kubapi_web:latest
          ports:
            - containerPort: 8080
