version: '3.8'
services:
  web:
    restart: unless-stopped
    build: .
    ports:
      - "8080:8080"
    environment:
        - ASPNETCORE_URLS=http://*:8080
        - ASPNETCORE_ENVIRONMENT=Development
